### ISSUE TITLE
multi-GPU handling ?

### ISSUE THREAD

**Issue by sandys** [patsissons/xmrig-nvidia-docker#2]
hi,
thanks for your work!
how do you run this in a system with multiple GPU ? does the miner handle it internally .. or does one have to run multiple docker instances with certain variables passed to it ?

**Comment by patsissons** [comment]
Probably better off asking this on the xmrig-nvidia repo, this is just a docker container for that project. As far as nvidia-docker is concerned, it should be able to detect multiple GPUs.

**Comment by sandys** [comment]
Hi
Thanks for replying.

So the way that  xmrig will handle it running in metal with multiple GPU is
different than how docker will handle it. That's why I thought I'll send it
to you.

Some other projects doing it will ask the user to run multiple docker
containers - each container bound to a specific GPU.

I'm hoping you had some thoughts about this. Sorry for the bother.

**Comment by patsissons** [comment]
No worries. I don't have a 2nd GPU to test with, but I have seen nvidia-docker demos that can see multiple GPUs in a single container. I suspect that means that a single container should be able to handle multiple GPUs, just not sure how to make it work exactly.

**Comment by catmeme** [comment]
Multi-GPU worked for me, it autodetected them, no problems.  Using CUDA 9, if that matters.

**Comment by patsissons** [comment]
@sandys I'm going to close this issue as @catmeme has confirmed multi-gpu support. I'll close it tomorrow unless you object.

**Comment by sandys** [comment]
please do! thanks!
P.S. I hope you are going to update the image for the new monero fork

**Comment by patsissons** [comment]
yup, i'll schedule a docker image build tonight.
