### ISSUE TITLE
Update to xmrig-nvidia 2.5.0 for March 28th Monero v7 PoW change

### ISSUE THREAD

**Issue by catmeme** [patsissons/xmrig-nvidia-docker#3]
In Monero's fight against ASICs, xmrig-nvidia 2.5.0 has been updated to account for the change in PoW that goes live on March 28th.

https://github.com/xmrig/xmrig/issues/434

**Comment by patsissons** [comment]
Thanks for the heads up, I will try and push a new docker image tonight.

**Comment by catmeme** [comment]
Awesome.  BTW, you probably don't get to hear this enough, I appreciate how you've structured this project.  Good work!

**Comment by patsissons** [comment]
Everything should be ready to go, give it a test and let me know how it goes. I'll be testing out my container updates tonight.

**Comment by catmeme** [comment]
confirmed working, cheers!
