### ISSUE TITLE
Update for donate-level.patch

### ISSUE THREAD

**Issue by bananajamma** [patsissons/xmrig-nvidia-docker#5]
The existing patch broke with [this commit](https://github.com/xmrig/xmrig-nvidia/commit/1ef3239535d71144b34b58d8587ac87210258582), here's an update:

```patch
diff --git a/src/donate.h b/src/donate.h
index 46f26b7..96e2251 100644
--- a/src/donate.h
+++ b/src/donate.h
@@ -44,7 +44,7 @@
  * BTC: 1P7ujsXeX7GxQwHNnJsRMgAdNkFZmNVqJT
  */
 constexpr const int kDefaultDonateLevel = 5;
-constexpr const int kMinimumDonateLevel = 1;
+constexpr const int kMinimumDonateLevel = 0;
 
 
 #endif /* __DONATE_H__ */
```

**Comment by patsissons** [comment]
Thanks I'll try and square this away later today

**Comment by bananajamma** [comment]
Missing some updates to PoW changes for other coins now too, another good reason to update.

**Comment by patsissons** [comment]
finally managed to get these builds out. tested it out this morning and everything looks good. I've upgraded the container to `cuda 9.2`  so it will required updating the installed nvidia drivers. let me know if you want a refresh for the `cuda 9.1` container as well.

**Comment by bananajamma** [comment]
I upgraded my system packages, and temporarily broke compatibility with other drivers / containers for a moment, so I took the opportunity to upgrade all my drivers, as well as CUDA to 9.2.  I don't need a 9.1, but it might not hurt for you to provide a 9.1 tag for those who aren't as masochistic.
