### ISSUE TITLE
Please update to 2.7.0-beta

### ISSUE THREAD

**Issue by bananajamma** [patsissons/xmrig-nvidia-docker#7]
https://github.com/xmrig/xmrig-nvidia/releases/tag/v2.7.0-beta

cheers!

**Comment by patsissons** [comment]
Is that in `master`?

**Comment by bananajamma** [comment]
Yes, you just need to trigger the build. :+1:

**Comment by patsissons** [comment]
`patsissons/xmrig-nvidia:9.2-devel` is up for testing (sorry for the delay I have been out of town for a about a week).
